name: semantic release

on:
  workflow_dispatch:
    branches:
      - master


jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: 'lts/*'

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
          cache: maven

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - run: "echo $HELM_PWD | helm registry login --username $HELM_USER --password-stdin $HELM_REGISTRY"
        env:
          HELM_USER: "github-actions"
          HELM_PWD: ${{ secrets.GITHUB_TOKEN }}
          HELM_REGISTRY: oci://ghcr.io/${{ github.repository }}

      - run: npm ci
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
