name: semantic release

on:
  workflow_dispatch:
    branches:
      - master

env:
  CR_OWNER: ${{ github.repository_owner }}
  CR_TOKEN: ${{ github.token }}

  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up npm
        uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: 'lts/*'
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
          cache: maven
      - name: Set up docker
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Set CR_GIT_REPO
        run: echo "CR_GIT_REPO=$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}')" >> $GITHUB_ENV
      - name: Set up chart-releaser
        uses: helm/chart-releaser-action@v1.4.0
        with:
          install_only: true
      - name: Set up git
        run: |
          git config user.email "semantic-release-bot@martynus.net"
          git config user.name "semantic-release-bot"

      - run: npm ci
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: "commit pom and chart.yaml"
        run: |
          git add pom.xml
          git add charts/Chart.yaml
          git commit -m "chore(release): [skip ci] next release" 
          git push
